/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { User } from "./types";
export namespace Components {
    interface DvButton {
    }
    interface DvUser {
        "user": User;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDvButtonElement extends Components.DvButton, HTMLStencilElement {
    }
    var HTMLDvButtonElement: {
        prototype: HTMLDvButtonElement;
        new (): HTMLDvButtonElement;
    };
    interface HTMLDvUserElement extends Components.DvUser, HTMLStencilElement {
    }
    var HTMLDvUserElement: {
        prototype: HTMLDvUserElement;
        new (): HTMLDvUserElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dv-button": HTMLDvButtonElement;
        "dv-user": HTMLDvUserElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DvButton {
    }
    interface DvUser {
        "user"?: User;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "dv-button": DvButton;
        "dv-user": DvUser;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dv-button": LocalJSX.DvButton & JSXBase.HTMLAttributes<HTMLDvButtonElement>;
            "dv-user": LocalJSX.DvUser & JSXBase.HTMLAttributes<HTMLDvUserElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
