/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DvClipboardCopy {
        "copyText": string;
    }
}
declare global {
    interface HTMLDvClipboardCopyElement extends Components.DvClipboardCopy, HTMLStencilElement {
    }
    var HTMLDvClipboardCopyElement: {
        prototype: HTMLDvClipboardCopyElement;
        new (): HTMLDvClipboardCopyElement;
    };
    interface HTMLElementTagNameMap {
        "dv-clipboard-copy": HTMLDvClipboardCopyElement;
    }
}
declare namespace LocalJSX {
    interface DvClipboardCopy {
        "copyText"?: string;
    }
    interface IntrinsicElements {
        "dv-clipboard-copy": DvClipboardCopy;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dv-clipboard-copy": LocalJSX.DvClipboardCopy & JSXBase.HTMLAttributes<HTMLDvClipboardCopyElement>;
        }
    }
}
